"""empty message

Revision ID: 59c106871e7b
Revises: None
Create Date: 2014-12-19 16:33:43.710001

"""

# revision identifiers, used by Alembic.
revision = '59c106871e7b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
